/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo;

public class Library {
    public boolean someLibraryMethod() {
        System.out.println("Lo logramos es una libreria");
        return true;
    }
}
